#! /bin/sh
### BEGIN INIT INFO
# Provides:          aria2c
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Should-Start:      aria2c
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=aria2c
DAEMON=/usr/bin/${NAME}
CONF=/etc/aria2/aria2.conf
DAEMON_OPTS="--conf-path=${CONF}"
DESC="${NAME}"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

start() {
    $DAEMON $DAEMON_OPTS
}

stop() {
    killall ${NAME}
}

case "$1" in
    start)
        log_begin_msg "Starting $DESC"
        start
        log_end_msg $?
    ;;
    stop)
        log_begin_msg "Stopping $DESC"
        stop
        log_end_msg $?
    ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
    ;;
esac
